### ISSUE TITLE
腾讯验证码更新了

### ISSUE THREAD

**Issue by huami1314** [Algortex/jkyz_yaohao#3]
找不到列子 暂时没人写出来啊啊啊

**Comment by ShorterTuxedo** [comment]
请自行接入打码平台

**Comment by ShorterTuxedo** [comment]
<img width="626" alt="image" src="https://user-images.githubusercontent.com/49613009/191386057-4072ac4b-81d7-48b0-a9cf-b5f7502e2888.png">

**Comment by ShorterTuxedo** [comment]
![image](https://user-images.githubusercontent.com/49613009/191399970-86032da8-b1be-40d8-b02a-9467714e8c73.png)
这就是vtt算法

**Comment by ShorterTuxedo** [comment]
没更新啊，我看它用的还是滑块

**Comment by ShorterTuxedo** [comment]
还是那个新的文字点选？

**Comment by huami1314** [comment]
> ![image](https://user-images.githubusercontent.com/49613009/191399970-86032da8-b1be-40d8-b02a-9467714e8c73.png)
> 这就是vtt算法

我的验证码是各种各样形状的滑块

**Comment by huami1314** [comment]
正方形滑块能过 其他三角形什么的过不了哈哈哈

**Comment by huami1314** [comment]
大佬们有没有推荐的腾讯验证码打码平台

**Comment by huami1314** [comment]
怎么我的是这种
![Uploading CB31FE01-92B9-4E48-98A0-087362790E1B.jpeg…]()

**Comment by huami1314** [comment]
为什么我的是这种
![3D90C995-F2C3-41CB-AA0E-395EFB4E5CC9](https://user-images.githubusercontent.com/99124359/192958364-25dd282f-59c1-4c6c-8fe8-c0abe75e6cec.jpeg)

**Comment by ShorterTuxedo** [comment]
这个能过，我有遇到过，有时候过不了

**Comment by ShorterTuxedo** [comment]
你调整一下坐标
