### ISSUE TITLE
你调整一下坐标

### ISSUE THREAD

**Issue by huami1314** [Algortex/jkyz_yaohao#4]
你调整一下坐标

_Originally posted by @Algortex in https://github.com/Algortex/jkyz_yaohao/issues/3#issuecomment-1262983104_
      反复调了几次，都不行 能不能给个列子 谢谢

**Comment by ShorterTuxedo** [comment]
截屏，打开selenium，在画图程序中找按钮的坐标就搞定了

**Comment by huami1314** [comment]
感谢感谢
